An application to assist people who are new at the University of Georgia and need to get from point A to B in the least time
on campus. The routes generated by this application will be a mix of walking paths and UGA bus routes so as to get from the 
source to destination in the least amount of time. The application also has a model to simulate bus delay i.e. bus delays
due to traffic, and suggests shorter walking routes instead if bus delays cause total travel time to increase. This random model 
can be replaced by a GPS-based service that tells where a bus is at any time to make exact predictions. The application would 
need database updates by an administrator if bus routes are added/removed/modified. Sample starter 
database included here.

DB Setup:
Open the DDLandDataDump.sql file on MySql server and execute the .sql file.

Two ways of running application:
1. You can deploy the war file (located inside the folder Project_folder\dist) on Glassfish server.
2. Open the Project in Netbeans IDE,
	include necessary jar files
	(gson-2.2.2.jar,  jgraph.jar, jgrapgt-0.8.3.jar, mysql-connector-java-5.1.23-bin.jar),
	Make connection with database on MySQL server,
	Set the connection properties(URL, USERNAME and PASSWORD) in Util.java file under Util package,
	Build the Project,
	Execute the Project.


